name: Build DotNet Project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    
    - name: Install .NET Framework 4.8 Reference Assemblies
      run: |
        sudo apt update
        sudo apt install -y dirmngr gnupg apt-transport-https ca-certificates software-properties-common
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        sudo apt-add-repository 'deb https://download.mono-project.com/repo/ubuntu stable-bionic main'
        sudo apt update
        sudo apt install -y mono-devel

    - name: Download Game References
      run: |
        mkdir -p lib
        wget -P lib "https://github.com/beat-forge/beatsaber-stripped/raw/main/versions/1.35.0/Beat%20Saber_Data/Managed/DataModels.dll"
        wget -P lib "https://github.com/beat-forge/beatsaber-stripped/raw/main/versions/1.35.0/Beat%20Saber_Data/Managed/HMLib.dll"
        wget -P lib "https://github.com/beat-forge/beatsaber-stripped/raw/main/versions/1.35.0/Beat%20Saber_Data/Managed/HMUI.dll"
        wget -P lib "https://github.com/beat-forge/beatsaber-stripped/raw/main/versions/1.35.0/Beat%20Saber_Data/Managed/Main.dll"
        wget -P lib "https://github.com/beat-forge/beatsaber-stripped/raw/main/versions/1.35.0/Beat%20Saber_Data/Managed/Unity.TextMeshPro.dll"
        wget -P lib "https://github.com/beat-forge/beatsaber-stripped/raw/main/versions/1.35.0/Beat%20Saber_Data/Managed/UnityEngine.dll"
        wget -P lib "https://github.com/beat-forge/beatsaber-stripped/raw/main/versions/1.35.0/Beat%20Saber_Data/Managed/UnityEngine.CoreModule.dll"
        wget -P lib "https://github.com/beat-forge/beatsaber-stripped/raw/main/versions/1.35.0/Beat%20Saber_Data/Managed/UnityEngine.UI.dll"
        wget -P lib "https://github.com/beat-forge/beatsaber-stripped/raw/main/versions/1.35.0/Beat%20Saber_Data/Managed/UnityEngine.UIElementsModule.dll"
        wget -P lib "https://github.com/beat-forge/beatsaber-stripped/raw/main/versions/1.35.0/Beat%20Saber_Data/Managed/UnityEngine.UIModule.dll"
        wget -P lib "https://github.com/beat-forge/beatsaber-stripped/raw/main/versions/1.35.0/Beat%20Saber_Data/Managed/UnityEngine.VRModule.dll"
        wget -P lib "https://github.com/beat-forge/beatsaber-stripped/raw/main/versions/1.35.0/Beat%20Saber_Data/Managed/Zenject.dll"
        wget -P lib "https://github.com/beat-forge/beatsaber-stripped/raw/main/versions/1.35.0/Beat%20Saber_Data/Managed/Zenject-usage.dll"

    - name: Download Plugin References
      run: |
        curl -LJO https://github.com/monkeymanboy/BeatSaberMarkupLanguage/releases/download/v1.9.2/BeatSaberMarkupLanguage-v1.9.2-RELEASE.zip
        curl -LJO https://github.com/nike4613/BeatSaber-IPA-Reloaded/releases/download/4.3.3/BSIPA-net472-x64.zip
        curl -LJO https://github.com/Auros/SiraUtil/releases/download/3.1.7/SiraUtil-3.1.7.zip

    - name: Extract Plugin References
      run: |
        unzip -q BeatSaberMarkupLanguage-v1.9.2-RELEASE.zip
        unzip -q BSIPA-net472-x64.zip
        unzip -q SiraUtil-3.1.7.zip

    - name: Create Counters+.csproj.user file
      run: |
        echo '<?xml version="1.0" encoding="utf-8"?>' > Counters+.csproj.user
        echo '<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">' >> Counters+.csproj.user
        echo '  <PropertyGroup>' >> Counters+.csproj.user
        echo '    <ReferencePath>' >> Counters+.csproj.user
        echo "      ${GITHUB_WORKSPACE}/lib;${GITHUB_WORKSPACE}/lib/Libs;${GITHUB_WORKSPACE}/lib/Plugins" >> Counters+.csproj.user
        echo '    </ReferencePath>' >> Counters+.csproj.user
        echo "    <BeatSaberDir>${GITHUB_WORKSPACE}/lib</BeatSaberDir>" >> Counters+.csproj.user
        echo '  </PropertyGroup>' >> Counters+.csproj.user
        echo '</Project>' >> Counters+.csproj.user

    - name: Build
      run: dotnet build
